version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
    working_directory: /go/src/github.com/vlsidlyarevich/gopher-cutter

    steps:
      - checkout
      - run:
          name: Code check
          command: |
            ls -al
      - run: make
