version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
      - image: circleci/mongo:4.1.9
    working_directory: /go/src/github.com/vlsidlyarevich/gopher-cutter

  steps:
    - checkout
    - run:
        name: Code check
        command: |
          ls -al
    - run:
        name: Waiting for MongoDB
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 27017 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MongoDB && exit 1

